#!/usr/bin/env bash
#Script transfers a file from a client to a server
#Takes 4 arguments. The path to the file, IP of the server to transfer
#+ the file to, the username of the server and the path to the privatekey
#+ the scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
