#!/usr/bin/env bash
#Configures Nginx on web-01 server and displays a 404 error message
#+ when GET request is used to request for the page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/custom_404.html'
sudo sed -i '/server_name _;/a \    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
