#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ but displays "Hi" at the 9th iteration using a while loop
#+ and if statement
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count == 9 ]
    then
         echo "Hi"
    fi
    count=$((count + 1))
done
