#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#+ but displays "bad luck" for the 4th iteration and "good luck"
#+ for the 8th using a while loop,
#+ and if, elif, else statements
count=1
while [ $count -le 10 ]
do
    if [ $count == 4 ]
    then
        echo "bad luck"
    elif [ $count == 8 ]
    then
	 echo "good luck"
    else
	echo "Best School"
      
    fi
    count=$((count + 1))
done
