#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
#+ but displays 4 and "bad luck from china" for the 4th iteration
#+ then displays 9 and "bad luck from Japan" for the 9th iteration
#+ and then displays 17 and "bad luck from Italy" for the 17th iteration
#+ using a while loop and case statements
count=1
while [ $count -le 20 ]
do
    echo "$count"
    case $count in
	4)
	    echo "bad luck from China";;
	9)
	    echo "bad luck from Japan";;
	17)
	    echo "bad luck from Italy";;
      
    esac
    
    count=$((count + 1))
done
