#!/usr/bin/env bash
# The bash script displays the content of the current directory
#+ in a list format and only the part of the name after
#+ the first dash is display

list=$(ls)

for i in $list; do

   echo "$i" | cut -d '-' -f 2

done
